---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(broom)
library(jsonlite)
library(scales)
library(cowplot)
```


```{r message=FALSE}
theme_set(theme_cowplot(font_size = 10, font_family = "serif")) 

# Positive values are in inferno, negative in viridis
scale_viridis_to_inferno = 
  function(..., 
           alpha = 1, values = NULL,
           midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar", aesthetics = aesthetics) {
    continuous_scale(
      aesthetics, "viridis_to_inferno",
      gradient_n_pal(c(viridis_pal(alpha, 0, 0.95, 1)(10), viridis_pal(alpha, 0.45, 1, direction=-1, option="inferno")(11)),
        #c(viridis_pal(1, 0.05, 0.9, -1)(11), viridis_pal(1, 0.25, 0.85, option="inferno")(10)),
        #c(viridis_pal(alpha, 0, 1, 1)(6), viridis_pal(alpha, 0.5, 1, direction=-1, option="inferno")(7)), 
                     values, space),
      na.value = na.value, guide = guide, ...,
      rescaler = function(x, to = c(0, 1), from = range(x, na.rm = TRUE)) { rescale_mid(x, to, from, midpoint) }
      )
  }
scale_fill_viridis_to_inferno = function(..., aesthetics = "fill") { scale_viridis_to_inferno(..., aesthetics = aesthetics) }
scale_color_viridis_to_inferno = function(..., aesthetics = "color") { scale_viridis_to_inferno(..., aesthetics = aesthetics) }

# scales to use for plots
scale_fill_neg_plot = scale_fill_viridis_c
scale_color_neg_plot = scale_color_viridis_c
scale_fill_pos_plot = function(...) { scale_fill_viridis_c(...,option="inferno", begin=1, end=0) }
scale_color_pos_plot = function(...) { scale_color_viridis_c(...,option="inferno", begin=1, end=0) }
scale_fill_div_plot = scale_fill_viridis_to_inferno #function(...) { scale_fill_gradient2(..., low = muted("blue"), high = muted("red")) }
scale_color_div_plot = scale_color_viridis_to_inferno #function(...) { scale_color_gradient2(..., low = muted("blue"), high = muted("red")) }

add_theme_elements = panel_border(colour="black", size=1) + theme(axis.line=element_blank(), aspect.ratio = 1, strip.background = element_blank())

tenx_format = trans_format("log10", math_format(10^.x))
```

## Read in data and plot crossing times and sweep times

```{r}
grid01 = read_csv("../output/grid_s0-1/grid.csv")
sweep01 = read_csv("../output/grid_s0-1_sweep/grid_sweep.csv")

grid001 = read_csv("../output/grid_s0-01/grid.csv")
sweep001 = read_csv("../output/grid_s0-01_sweep/grid_sweep.csv")

ssigma = read_csv("../output/grid_ssigma/grid.csv")

# put data from multiple runs into single dataframe
grid = full_join(grid01, grid001)
# for duplicate delta values, keep only data from the first run to keep sample size even
sweep001_only = anti_join(sweep001, sweep01, by=c("K", "delta", "sigma", "rep"))
sweep = full_join(sweep01, sweep001_only)
```

### Plot crossing time and sweep time

```{r}
grid %>% group_by(K, delta, sigma, s) %>% summarize(m_crossing_time = log10(mean(crossing_time))) %>% 
  ggplot(aes(x=delta, y=K)) + 
  geom_raster(aes(fill=m_crossing_time)) + 
  scale_x_log10() + scale_y_log10() + add_theme_elements + 
  labs(x = expression(delta), y = "N") +
  scale_fill_plot(name = "Crossing time") +
  facet_grid(s~sigma, labeller = label_bquote(rows=s==.(s), cols=sigma==.(sigma)))

sweep %>% group_by(K, delta, sigma) %>% summarize(m_sweep_time = mean(crossing_time)) %>% mutate(sval = -delta) %>%
  ggplot(aes(x=sval, y=K)) + 
  geom_raster(aes(fill=m_sweep_time)) + 
  scale_x_log10() + scale_y_log10() + add_theme_elements + 
  labs(x = "s", y = "N") +
  scale_fill_plot(name = "Sweep time", trans = "log10") +
  facet_wrap(~sigma, labeller = label_bquote(sigma==.(sigma)))

p.ctime = grid %>% filter(s==0.1) %>% group_by(K, delta, sigma, s) %>% summarize(m_crossing_time = log10(mean(crossing_time))) %>% 
  ggplot(aes(x=delta, y=K)) + 
  geom_raster(aes(fill=m_crossing_time)) + 
  scale_x_log10() + scale_y_log10() + add_theme_elements + 
  labs(x = expression(delta), y = expression(italic(N))) +
  scale_fill_pos_plot(name = expression(log[10](tau))) + scale_color_pos_plot(guide=FALSE) +
  facet_grid(.~sigma, labeller = label_bquote(cols=sigma==.(sigma)))
p.ctime

ggsave("../output/log_tau_s0-1.pdf", p.ctime, width=6, units="in")
```

### Plot ratio of sweep times 

```{r}
sweep %>% group_by(K, delta, sigma) %>% summarize(m_sweep_time = mean(crossing_time)) %>% ungroup() %>% mutate(sval = -delta) %>%
  select(K,sigma,sval,m_sweep_time) %>% spread(sigma, m_sweep_time) %>% mutate(ratio = `0.05`/`5e-08`) %>%
  ggplot(aes(x=sval, y=K)) + 
  geom_raster(aes(fill=ratio)) + 
  scale_x_log10() + scale_y_log10() + annotation_logticks() + add_theme_elements + 
  labs(x = "s", y = "N") +
  scale_fill_plot(name = "Ratio of sweep times", trans = "log10")
```

## Join together mean crossing time and sweep time and create alpha values

```{r}
g = grid %>% group_by(K, delta, sigma, s) %>% summarize(m_crossing_time = mean(crossing_time)) %>% ungroup() %>% select(K,sigma,m_crossing_time,delta,s)
s = sweep %>% group_by(K, delta, sigma) %>% summarize(m_sweep_time = mean(crossing_time)) %>% ungroup() %>% mutate(sval = -delta) %>% select(K,sval,sigma,m_sweep_time)

gs = full_join(g, s, by=c("K","sigma")) %>% mutate(alpha=m_crossing_time/m_sweep_time)
```

### Plot log(alpha) as a function of N, delta, and sigma

```{r}
gs %>% filter(s==0.1, sval!=0.001) %>%
  ggplot(aes(x=delta, y=K)) + 
  geom_tile(aes(fill=log10(alpha), color=log10(alpha))) + 
  scale_x_log10(labels=tenx_format) + scale_y_log10(labels=tenx_format) + add_theme_elements + 
  labs(x = expression(italic(N)), y = expression(delta)) +
  scale_fill_div_plot(name = expression(log[10](italic(alpha[sigma])))) + scale_color_div_plot(guide=FALSE) +
  facet_grid(sval~sigma, labeller = label_bquote(rows=italic(s)[sweep]==.(sval), cols=sigma==.(sigma)))

p.logalpha = gs %>% filter(s==0.1, sval==0.1) %>%
  ggplot(aes(x=delta, y=K)) + 
  geom_tile(aes(fill=log10(alpha), color=log10(alpha))) + 
  scale_x_log10(labels=tenx_format) + scale_y_log10(labels=tenx_format) + add_theme_elements + 
  labs(x = expression(italic(N)), y = expression(delta)) +
  scale_fill_pos_plot(limits = c(0, 3.2), name = expression(log[10](italic(alpha[sigma])))) + scale_color_pos_plot(guide=FALSE) +
  facet_grid(.~sigma, labeller = label_bquote(cols=sigma==.(sigma)))
p.logalpha

ggsave("../output/log_alpha_s0-1.pdf", p.logalpha, width=6, units="in")
```

### Plot log ratio of alphas

```{r}
p.logratio = gs %>% filter(s==0.1, sval!=0.001) %>%
  select(K,sigma,delta,sval,alpha) %>% spread(sigma, alpha) %>% 
  mutate(`0.05` = log10(`0.05`/`5e-08`), `0.5` = log10(`0.5`/`5e-08`)) %>% 
  gather(`0.05`, `0.5`, key = sigma, value = ratio) %>%
  ggplot(aes(x=delta, y=K)) + 
  geom_tile(aes(fill=ratio, color=ratio)) + 
  scale_x_log10(labels=tenx_format) + scale_y_log10(labels=tenx_format) + add_theme_elements + 
  labs(x = expression(delta), y = expression(italic(N))) +
  scale_fill_div_plot(name = expression(log[10](italic(alpha[sigma])/italic(alpha[5e-08])))) + scale_color_div_plot(guide=FALSE) +
  facet_grid(sigma~sval, labeller = label_bquote(rows=sigma==.(sigma), cols=italic(s)[sweep]==.(sval)))
p.logratio

ggsave("../output/log_ratio_s0-1.pdf", p.logratio, width=6, units="in")
```

### Plot crossing times as a function of s and sigma

```{r}
ss = ssigma %>% group_by(mu1, s, sigma) %>% summarize(m_crossing_time = mean(crossing_time)) %>% ungroup() %>% mutate(ratio=log10(m_crossing_time*mu1))

p.ss = ss %>%
  ggplot(aes(x=s, y=sigma)) + 
  geom_tile(aes(fill=ratio, color=ratio)) + 
  geom_abline(slope = 1, linetype = 2) +
  scale_x_log10(labels=tenx_format) + scale_y_log10(labels=tenx_format) + add_theme_elements + 
  labs(x = expression(italic(s)), y = expression(italic(sigma))) +
  scale_fill_div_plot(name = expression(log[10](tau*mu[1]))) + scale_color_div_plot(guide=FALSE) +
  facet_grid(.~mu1, labeller = label_bquote(cols=italic(mu[1])==.(mu1)))
p.ss

ggsave("../output/log_taumu.pdf", p.ss, width=6, units="in")
```

